version: 1.0.{build}
skip_non_tags: true
image: WMF 5
services: mssql2014
build:
  verbosity: minimal
install:
  - cinst pester
build_script:
  - ps: & $Env:APPVEYOR_BUILD_FOLDER\source\tests\Set-AppveyorSQL.ps1

  
test_script:
  - ps: $res = Invoke-Pester -Path $Env:APPVEYOR_BUILD_FOLDER -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $Env:APPVEYOR_BUILD_FOLDER\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

